### ISSUE TITLE
plugin loading: sort glob() output alphabetically by basename

### ISSUE THREAD

**Issue by binary1230** [magfest/sideboard#15]
See https://github.com/magfest/sideboard/issues/13#issuecomment-221462978 for a discussion on why this is a good idea.

This line here in imports.py:
```plugin_dirs = [d for d in glob(join(config['plugins_dir'], '*')) if isdir(d) and not basename(d).startswith('_')]```

returns a list of plugin directories it finds, sorted in no particular order (glob() is unsorted)

Sideboard later prioritizes some of the items in this list to ensure a proper load order, BUT, the unprioritized ones can be loaded in a different order in different systems.

In THEORY this never matters, but, if we sorted the unprioritized plugins alphabetically, then the load order will be the same on all systems and reduce the chance that we could ever see weird system-specific bugs that appear to only happen on one machine and not the other.

This is kind of low priority and me being paranoid and overkill BUT still a useful and simple thing we can do to decrease the chance of encountering subtle heisenberg bugs later on.

**Comment by thaeli** [comment]
If we're sorting them alphabetically anyway, any reason to not get rid of priority_plugins and just name the plugins in the order you want them loaded? That way you don't have to touch the Sideboard config every time you change plugins.

**Comment by binary1230** [comment]
in theory most plugins don't require a specific ordering, just ones that depend on others like tabletop depends on panels, all of them depend on uber. 

so I'd expect priority_plugins should be a minimal list of 1-2 plugins, whereas for mag we have 9ish plugins now and don't need to list them all explicitly anywhere in the INI.

so sideboard should take in the following two lists:
- alphabetized list of plugins it finds on the disk (length: 9ish)
- priority_plugins list (length: 1 or 2)

and then from there generate a prioritized list that it loads in that order.

**Comment by EliAndrewC** [comment]
> If we're sorting them alphabetically anyway, any reason to not get rid of priority_plugins and just name the plugins in the order you want them loaded? That way you don't have to touch the Sideboard config every time you change plugins.

I'd rather be able to keep plugin names as whatever we would otherwise want to name them without having to be limited to something later in the alphabet.

With that being said, plugin authors could certainly choose to rely on the sort behavior and never bother setting ``priority_plugins`` if that's what they preferred.
