### ISSUE TITLE
Use minimum rather than pinned dependencies

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/sideboard#25]
Sideboard currently has a `requirements.txt` file
(https://github.com/magfest/sideboard/blob/master/requirements.txt)
which pins all of its dependencies.  I've learned over time that a lot of Python packaging utilities (in particular `setuptools` and `pkg_resources`) enforce these dependencies.

This causes problems in the following situation:
- Sideboard pins a default version of a library, e.g. `SQLAlchemy==1.0.0`.
- Sideboard plugin pins a dependency at a higher version, e.g. `SQLAlchemy==1.0.12`.
- Everything installs, but then when we try to run a command like `sep`, we get an error in something like `pkg_resources.load_entry_point` because it iterates through the `requirements.txt` file and finds a mismatch.

In theory we could monkeypatch `pkg_resources` and maybe whatever part of `setuptools` are enforcing this restriction.

However, I've been doing a lot of Googling on this, and the consensus seems to be, "pinning dependencies is good for applications and bad for libraries".  In other words, "this is a feature not a bug" and Sideboard should instead be enforcing minimum dependencies.

I'm going to experiment to see if this causes a different set of issues.  I'm concerned about the following situation:
- Sideboard specifies a minimum dependency such as `SQLAlchemy>=1.0.0`.
- Sideboard plugin pins a dependency at a higher version, e.g. `SQLAlchemy==1.0.12`.
- We run `python setup.py develop` on Sideboard itself and install an even later version, e.g. `SQLAlchemy 1.0.15`.
- We run `python setup.py develop` on the plugin, which pins an earlier version, which will hopefully Just Work but we'll see.

Assuming this general approach proves valid, I'll update Sideboard's `requirements.txt` file to change all of the dependencies from `==` to `>=`.  I'll run the unit tests for Sideboard and also for all the plugins I've got here at my work.  I don't expect this to break anything, but I'll let you know if there seems to be any potential to that prior to opening the PR.

**Comment by binary1230** [comment]
Cool this from some quick looking around seems to be the right call

**Comment by EliAndrewC** [comment]
In general, this seems to be working great!

The specific problem I'm currently running into is that some of the Sideboard plugins where I work still run on legacy CentOS 5 systems.  Evidently the latest version of ``libcap-devel`` supported by CentOS 5 is ``1.10-26``
(http://www.rpmseek.com/rpm-pl/libcap.html?hl=com&cx=0%3A-%3A0%3A0%3A0%3A0%3A0&qArStr=0&qRtStr=0&qDnStr=103)
which doesn't support ``python-prctl``.

(Side note: the bug relating to this is https://bugzilla.redhat.com/show_bug.cgi?id=483548 and the bug name is ``<sys/capability.h> is a complete disaster of a header" which is one of the better bug names I've ever seen.)

As it happens, Python allows us to specify optional dependencies via the ``extras_require`` option in ``setup.py`` (https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).  To make this work, we'd remove ``python-prctl`` and ``psutil`` from ``requirements.txt`` and instead add this to ``setup.py``:

```python
        extras_require={
            'perftrace': ['python-prctl>=1.6.1', 'psutil>=4.3.0']
        }
```

That would cause ``python-prctl`` to NOT be installed by default.  However, when installing dependencies, we can say e.g. ``pip install -e .[perftrace]`` to install all the dependencies for performance tracing.  (I'll need to double-check how our ``ubersystem-puppet`` deploy stuff installs dependencies, since this might require an extra step to be added to that.)

To make this work, I'll also make a small change to ``sideboard/lib/_threads.py`` to make setting names on threads something that only happens if those modules are present.  This will be backwards-compatible with what we have now, and continue to work on legacy systems.  (Another side note: it's absurd that we still have legacy deployments on a 12-year-old version of CentOS, but I guess it's cool that stuff is supported for that long.)

This will all be part of the PR that I'll make later this week.  This will probably be a big enough change that we'll probably want to wait until next week after MAGLabs to actually consider merging and deploying it.

**Comment by binary1230** [comment]
btw, we install dependencies with puppet by running ```paver install_deps``` or whatever that command is.  so if paver does the right thing with the extra_requires, then we're good to go

**Comment by EliAndrewC** [comment]
> btw, we install dependencies with puppet by running ``paver install_deps`` or whatever that command is. so if paver does the right thing with the extra_requires, then we're good to go

Well the point is that the "correct thing" is to NOT install those by default, because they're only dependencies for people who care about this feature.  We therefore do need to add ``pip install -e .[perftrace]`` in order to say "yes we do actually care about these dependencies".
