### ISSUE TITLE
check_connections fails on Python 3

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/sideboard#45]
The following line works in Python 2 but not Python 3 (from ``connection_checker.py``):

```
jproxy = jservice._send.im_self  # ugly kludge to get the ServerProxy object
```

Apparently there's some Python 3 equivalent to this which we'll need to try.

**Comment by binary1230** [comment]
hmmmm would this explain why all the sideboard unit tests that try to run a daemon are always failing?

**Comment by EliAndrewC** [comment]
I wouldn't expect this would affect our tests, because this line is in a single function that's not called by Sideboard unless someone explicitly invokes ``sep check_connections`` or visits http://server/check_connections
